[2024-09-15T03:22:07.769+0000] {processor.py:186} INFO - Started process (PID=55) to work on /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:22:07.773+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/modules/__init__.py for tasks to queue
[2024-09-15T03:22:07.780+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:22:07.779+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:22:07.839+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:22:07.819+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/modules/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T03:22:07.847+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:22:07.918+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/modules/__init__.py took 0.182 seconds
[2024-09-15T03:22:41.889+0000] {processor.py:186} INFO - Started process (PID=63) to work on /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:22:41.894+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/modules/__init__.py for tasks to queue
[2024-09-15T03:22:41.918+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:22:41.916+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:22:41.970+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:22:41.953+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/modules/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T03:22:41.974+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:22:42.086+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/modules/__init__.py took 3.639 seconds
[2024-09-15T03:24:36.642+0000] {processor.py:186} INFO - Started process (PID=60) to work on /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:24:36.653+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/modules/__init__.py for tasks to queue
[2024-09-15T03:24:36.672+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:24:36.671+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:24:36.713+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:24:36.701+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/modules/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T03:24:36.717+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:24:36.866+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/modules/__init__.py took 0.454 seconds
[2024-09-15T03:25:07.428+0000] {processor.py:186} INFO - Started process (PID=68) to work on /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:25:07.431+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/modules/__init__.py for tasks to queue
[2024-09-15T03:25:07.442+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:25:07.440+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:25:07.474+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:25:07.468+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/modules/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T03:25:07.477+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:25:07.536+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/modules/__init__.py took 0.138 seconds
[2024-09-15T03:25:38.193+0000] {processor.py:186} INFO - Started process (PID=75) to work on /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:25:38.197+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/modules/__init__.py for tasks to queue
[2024-09-15T03:25:38.215+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:25:38.214+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:25:38.626+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:25:38.601+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/modules/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T03:25:38.658+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:25:39.339+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/modules/__init__.py took 1.430 seconds
[2024-09-15T03:26:10.529+0000] {processor.py:186} INFO - Started process (PID=83) to work on /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:26:10.531+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/modules/__init__.py for tasks to queue
[2024-09-15T03:26:10.542+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:26:10.540+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:26:10.637+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:26:10.613+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/modules/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T03:26:10.641+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:26:10.705+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/modules/__init__.py took 0.202 seconds
[2024-09-15T03:26:41.123+0000] {processor.py:186} INFO - Started process (PID=91) to work on /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:26:41.124+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/modules/__init__.py for tasks to queue
[2024-09-15T03:26:41.127+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:26:41.126+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:26:41.952+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:26:41.141+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/modules/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T03:26:41.954+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:26:42.032+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/modules/__init__.py took 0.914 seconds
[2024-09-15T03:27:12.813+0000] {processor.py:186} INFO - Started process (PID=99) to work on /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:27:12.815+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/modules/__init__.py for tasks to queue
[2024-09-15T03:27:12.818+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:27:12.818+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:27:12.839+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:27:12.833+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/modules/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T03:27:12.841+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:27:12.865+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/modules/__init__.py took 0.058 seconds
[2024-09-15T03:27:43.386+0000] {processor.py:186} INFO - Started process (PID=107) to work on /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:27:43.389+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/modules/__init__.py for tasks to queue
[2024-09-15T03:27:43.392+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:27:43.392+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:27:43.411+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:27:43.406+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/modules/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T03:27:43.413+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:27:43.433+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/modules/__init__.py took 0.055 seconds
[2024-09-15T03:28:13.575+0000] {processor.py:186} INFO - Started process (PID=115) to work on /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:28:13.577+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/modules/__init__.py for tasks to queue
[2024-09-15T03:28:13.582+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:28:13.582+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:28:13.609+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:28:13.604+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/modules/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T03:28:13.611+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:28:13.636+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/modules/__init__.py took 0.067 seconds
[2024-09-15T03:28:43.991+0000] {processor.py:186} INFO - Started process (PID=123) to work on /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:28:43.993+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/modules/__init__.py for tasks to queue
[2024-09-15T03:28:43.996+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:28:43.995+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:28:44.020+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:28:44.014+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/modules/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T03:28:44.022+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:28:44.039+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/modules/__init__.py took 0.053 seconds
[2024-09-15T03:29:14.442+0000] {processor.py:186} INFO - Started process (PID=131) to work on /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:29:14.443+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/modules/__init__.py for tasks to queue
[2024-09-15T03:29:14.445+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:29:14.445+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:29:14.460+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:29:14.455+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/modules/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T03:29:14.462+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:29:14.479+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/modules/__init__.py took 0.042 seconds
[2024-09-15T03:29:45.511+0000] {processor.py:186} INFO - Started process (PID=140) to work on /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:29:45.513+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/modules/__init__.py for tasks to queue
[2024-09-15T03:29:45.523+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:29:45.523+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:29:45.552+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:29:45.544+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/modules/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T03:29:45.555+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:29:45.583+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/modules/__init__.py took 0.091 seconds
[2024-09-15T03:30:16.049+0000] {processor.py:186} INFO - Started process (PID=148) to work on /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:30:16.050+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/modules/__init__.py for tasks to queue
[2024-09-15T03:30:16.054+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:30:16.053+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:30:16.081+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:30:16.063+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/modules/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T03:30:16.083+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:30:16.100+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/modules/__init__.py took 0.058 seconds
[2024-09-15T03:30:46.480+0000] {processor.py:186} INFO - Started process (PID=156) to work on /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:30:46.482+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/modules/__init__.py for tasks to queue
[2024-09-15T03:30:46.485+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:30:46.485+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:30:46.509+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:30:46.504+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/modules/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T03:30:46.512+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:30:46.540+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/modules/__init__.py took 0.066 seconds
[2024-09-15T03:31:16.896+0000] {processor.py:186} INFO - Started process (PID=163) to work on /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:31:16.897+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/modules/__init__.py for tasks to queue
[2024-09-15T03:31:16.901+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:31:16.900+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:31:16.923+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:31:16.919+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/modules/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T03:31:16.925+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:31:16.943+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/modules/__init__.py took 0.057 seconds
[2024-09-15T03:31:47.373+0000] {processor.py:186} INFO - Started process (PID=171) to work on /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:31:47.375+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/modules/__init__.py for tasks to queue
[2024-09-15T03:31:47.378+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:31:47.377+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:31:47.396+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:31:47.393+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/modules/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T03:31:47.397+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:31:47.415+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/modules/__init__.py took 0.048 seconds
[2024-09-15T03:32:17.784+0000] {processor.py:186} INFO - Started process (PID=179) to work on /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:32:17.786+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/modules/__init__.py for tasks to queue
[2024-09-15T03:32:17.788+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:32:17.788+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:32:17.814+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:32:17.809+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/modules/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T03:32:17.816+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:32:17.840+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/modules/__init__.py took 0.063 seconds
[2024-09-15T03:32:48.215+0000] {processor.py:186} INFO - Started process (PID=187) to work on /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:32:48.217+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/modules/__init__.py for tasks to queue
[2024-09-15T03:32:48.220+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:32:48.220+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:32:48.241+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:32:48.237+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/modules/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T03:32:48.243+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:32:48.269+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/modules/__init__.py took 0.061 seconds
[2024-09-15T03:33:18.702+0000] {processor.py:186} INFO - Started process (PID=195) to work on /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:33:18.703+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/modules/__init__.py for tasks to queue
[2024-09-15T03:33:18.708+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:33:18.707+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:33:18.738+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:33:18.734+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/modules/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T03:33:18.742+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:33:18.783+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/modules/__init__.py took 0.093 seconds
[2024-09-15T03:33:49.066+0000] {processor.py:186} INFO - Started process (PID=203) to work on /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:33:49.068+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/modules/__init__.py for tasks to queue
[2024-09-15T03:33:49.071+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:33:49.070+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:33:49.092+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:33:49.087+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/modules/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T03:33:49.093+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:33:49.117+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/modules/__init__.py took 0.056 seconds
[2024-09-15T03:34:19.465+0000] {processor.py:186} INFO - Started process (PID=212) to work on /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:34:19.467+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/modules/__init__.py for tasks to queue
[2024-09-15T03:34:19.470+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:34:19.470+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:34:19.488+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:34:19.482+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/modules/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T03:34:19.490+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:34:19.508+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/modules/__init__.py took 0.048 seconds
[2024-09-15T03:34:49.947+0000] {processor.py:186} INFO - Started process (PID=220) to work on /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:34:49.948+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/modules/__init__.py for tasks to queue
[2024-09-15T03:34:49.951+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:34:49.950+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:34:49.973+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:34:49.969+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/modules/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T03:34:49.975+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:34:49.994+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/modules/__init__.py took 0.054 seconds
[2024-09-15T03:48:01.350+0000] {processor.py:186} INFO - Started process (PID=62) to work on /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:48:01.351+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/modules/__init__.py for tasks to queue
[2024-09-15T03:48:01.355+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:48:01.355+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:48:16.598+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:48:14.138+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/modules/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/__init__.py", line 3, in <module>
    from .build_dataframe import creacion_df
  File "/opt/airflow/dags/modules/build_dataframe.py", line 8, in <module>
    import obtencion_datos
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T03:48:16.602+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:48:17.453+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/modules/__init__.py took 16.080 seconds
[2024-09-15T03:48:47.973+0000] {processor.py:186} INFO - Started process (PID=72) to work on /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:48:47.975+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/modules/__init__.py for tasks to queue
[2024-09-15T03:48:47.990+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:48:47.987+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:48:49.232+0000] {logging_mixin.py:190} INFO - [2024-09-15T03:48:49.223+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/modules/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/__init__.py", line 3, in <module>
    from .build_dataframe import creacion_df
  File "/opt/airflow/dags/modules/build_dataframe.py", line 8, in <module>
    import obtencion_datos
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T03:48:49.235+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/__init__.py
[2024-09-15T03:48:49.263+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/modules/__init__.py took 1.332 seconds
[2024-09-15T23:27:39.698+0000] {processor.py:186} INFO - Started process (PID=54) to work on /opt/airflow/dags/modules/__init__.py
[2024-09-15T23:27:39.706+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/modules/__init__.py for tasks to queue
[2024-09-15T23:27:39.729+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:27:39.728+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/modules/__init__.py
[2024-09-15T23:27:39.972+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:27:39.935+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/modules/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T23:27:39.994+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/__init__.py
[2024-09-15T23:27:40.124+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/modules/__init__.py took 0.450 seconds
[2024-09-15T23:28:11.039+0000] {processor.py:186} INFO - Started process (PID=62) to work on /opt/airflow/dags/modules/__init__.py
[2024-09-15T23:28:11.042+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/modules/__init__.py for tasks to queue
[2024-09-15T23:28:11.061+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:28:11.060+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/modules/__init__.py
[2024-09-15T23:28:11.096+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:28:11.087+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/modules/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T23:28:11.103+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/__init__.py
[2024-09-15T23:28:11.174+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/modules/__init__.py took 0.173 seconds
[2024-09-15T23:28:41.311+0000] {processor.py:186} INFO - Started process (PID=70) to work on /opt/airflow/dags/modules/__init__.py
[2024-09-15T23:28:41.312+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/modules/__init__.py for tasks to queue
[2024-09-15T23:28:41.316+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:28:41.316+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/modules/__init__.py
[2024-09-15T23:28:41.347+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:28:41.341+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/modules/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T23:28:41.349+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/__init__.py
[2024-09-15T23:28:41.374+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/modules/__init__.py took 0.074 seconds
[2024-09-15T23:29:12.038+0000] {processor.py:186} INFO - Started process (PID=78) to work on /opt/airflow/dags/modules/__init__.py
[2024-09-15T23:29:12.040+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/modules/__init__.py for tasks to queue
[2024-09-15T23:29:12.044+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:29:12.043+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/modules/__init__.py
[2024-09-15T23:29:12.076+0000] {logging_mixin.py:190} INFO - [2024-09-15T23:29:12.071+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/modules/__init__.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/modules/__init__.py", line 1, in <module>
    from obtencion_datos import llamado_api
ModuleNotFoundError: No module named 'obtencion_datos'
[2024-09-15T23:29:12.078+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/modules/__init__.py
[2024-09-15T23:29:12.098+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/modules/__init__.py took 0.066 seconds
